answerly/urls.py
from django.contrib import admin
from django.urls import path, include

import qanda.urls
import user.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('', include(qanda.urls, namespace='qanda')),
]

qanda/urls.py
from django.urls import path

from qanda import views

app_name = 'qanda'

urlpatterns = [
    path('ask', views.AskQuestionView.as_view(), name='ask'),
    path('q/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
    path('q/<int:pk>/answer', views.CreateAnswerView.as_view(), name='answer_question'),
    path('q/search', views.SearchView.as_view(), name='question_search'),
    path('a/<int:pk>/accept', views.UpdateAnswerAcceptance.as_view(), name='update_answer_acceptance'),
    path('daily/<int:year>/<int:month>/<int:day>', views.DailyQuestionList.as_view(), name='daily_questions'),
    path('days', views.AllDaysWithQuestions.as_view(), name='days'),
    path('', views.TodaysQuestionList.as_view(), name='index'),
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register', views.RegisterView.as_view(), name='register'),
]

qanda/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from qanda import elasticsearch


class Question(models.Model):
    title = models.CharField(max_length=140)
    question = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('qanda:question_detail', kwargs={'pk': self.id})

    def can_accept_answers(self, user):
        return user == self.user

    def as_elasticsearch_dict(self):
        return {
            '_id': self.id,
            '_type': 'doc',
            'text': '{}\n{}'.format(self.title, self.question),
            'question_body': self.question,
            'title': self.title,
            'id': self.id,
            'created': self.created,
        }

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
        elasticsearch.upsert(self)


class Answer(models.Model):
    answer = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(to=Question, on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

user/models.py
from django.db import models

# Create your models here.

qanda/forms.py
from django import forms
from django.contrib.auth import get_user_model

from qanda.models import Question, Answer


class QuestionForm(forms.ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput,
                                  queryset=get_user_model().objects.all(),
                                  disabled=True,
                                  )

    class Meta:
        model = Question
        fields = ['title', 'question', 'user']


class AnswerForm(forms.ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput,
                                  queryset=get_user_model().objects.all(),
                                  disabled=True,
                                  )

    question = forms.ModelChoiceField(widget=forms.HiddenInput,
                                      queryset=Question.objects.all(),
                                      disabled=True,
                                      )

    class Meta:
        model = Answer
        fields = ['answer', 'user', 'question']


class AnswerAcceptanceForm(forms.ModelForm):
    accepted = forms.BooleanField(widget=forms.HiddenInput,
                                  required=False,
                                  )

    class Meta:
        model = Answer
        fields = ['accepted', ]

qanda/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views.generic import CreateView, DetailView, UpdateView, DayArchiveView, RedirectView, TemplateView

from qanda.elasticsearch import search_for_questions
from qanda.forms import QuestionForm, AnswerAcceptanceForm, AnswerForm
from qanda.models import Question, Answer


class AskQuestionView(LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    template_name = 'qanda/ask.html'

    def get_initial(self):
        return {'user': self.request.user.id}

    def form_valid(self, form):
        action = self.request.POST.get('action')

        if action == 'SAVE':
            return super().form_valid(form)
        elif action == 'PREVIEW':
            preview = Question(question=form.cleaned_data['question'],
                               title=form.cleaned_data['title'])
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)

        return HttpResponseBadRequest()


class QuestionDetailView(DetailView):
    model = Question

    accept_form = AnswerAcceptanceForm(initial={'accepted': True})
    reject_form = AnswerAcceptanceForm(initial={'accepted': False})

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        ctx.update({
            'answer_form': AnswerForm(initial={
                'user': self.request.user.id,
                'question': self.object.id})
        })

        if self.object.can_accept_answers(self.request.user):
            ctx.update({
                'accept_form': self.accept_form,
                'reject_form': self.reject_form,
            })

        return ctx


class CreateAnswerView(LoginRequiredMixin, CreateView):
    form_class = AnswerForm
    template_name = 'qanda/create_answer.html'

    def get_initial(self):
        return {
            'question': self.get_question().id,
            'user': self.request.user.id,
        }

    def get_context_data(self, **kwargs):
        return super().get_context_data(question=self.get_question(), **kwargs)

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_valid(self, form):
        action = self.request.POST.get('action')

        if action == 'SAVE':
            return super().form_valid(form)
        elif action == 'PREVIEW':
            ctx = self.get_context_data(preview=form.cleaned_data['answer'])
            return self.render_to_response(context=ctx)

        return HttpResponseBadRequest()

    def get_question(self):
        return Question.objects.get(pk=self.kwargs['pk'])


class UpdateAnswerAcceptance(LoginRequiredMixin, UpdateView):
    form_class = AnswerAcceptanceForm
    queryset = Answer.objects.all()

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_invalid(self, form):
        return HttpResponseRedirect(redirect_to=self.object.question.get_absolute_url())


class DailyQuestionList(DayArchiveView):
    queryset = Question.objects.all()
    date_field = 'created'
    month_format = '%m'
    allow_empty = True


class TodaysQuestionList(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        today = timezone.now()
        return reverse('qanda:daily_questions', kwargs={'day': today.day,
                                                        'month': today.month,
                                                        'year': today.year,
                                                        })


class AllDaysWithQuestions(TemplateView):
    template_name = 'qanda/all_days.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dates'] = Question.objects.values_list('created__date', flat=True).distinct()
        return context


class SearchView(TemplateView):
    template_name = 'qanda/search.html'

    def get_context_data(self, **kwargs):
        query = self.request.GET.get('q', None)
        ctx = super().get_context_data(query=query, **kwargs)

        if query:
            results = search_for_questions(query)
            ctx['hits'] = results

        return ctx

user/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView


class RegisterView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = 'qanda:index'

qanda/templates/qanda/all_days.html
{% extends 'base.html' %}

{% block body %}
    <div class="col-sm-12">
        <h1> Here are all the days </h1>

        <ul>
            {% for date in dates %}
                <li>
                    <a href="{% url 'qanda:daily_questions' year=date.year month=date.month day=date.day %}"> {{ date }} </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

qanda/templates/qanda/ask.html
{% extends 'base.html' %}

{% load markdownify %}
{% load crispy_forms_tags %}

{% block title %}
    Ask a question
{% endblock %}

{% block body %}
    <div class="col-md-12">
        <h1> Ask a question </h1>
        {% if preview %}
            <div class="card question-preview">
                <div class="card-header"> Question Preview</div>
                <div class="card-body">
                    <h1 class="card-title"> {{ preview.title }}</h1>
                    {{ preview.question | markdownify }}
                </div>
            </div>
        {% endif %}

        <form method="POST">
            {{ form | crispy }}
            {% csrf_token %}
            <button class="btn btn-primary" type="submit" name="action" value="PREVIEW"> Preview</button>
            <button class="btn btn-primary" type="submit" name="action" value="SAVE"> Ask !</button>
        </form>

    </div>
{% endblock %}

qanda/templates/qanda/common/display_question.html
{% load markdownify %}

<div class="question">
    <div class="meta col-sm-12">
        <h1> {{ question.title }} </h1>
        Asked by {{ question.user }} on {{ question.created }}
    </div>

    <div class="body col-sm-12">
        {{ question.question | markdownify }}
    </div>
</div>

qanda/templates/qanda/common/list_answers.html
{% load markdownify %}

<h3> Answers </h3>

<ul class="list-unstyled answers">
    {% for answer in question.answer_set.all %}
        <li class="answer row">
            <div class="col-sm-3 col-md-2 text-center">
                {% if answer.accepted %}
                    <span class="badge badge-pill badge-succes"> Accepted </span>
                {% endif %}

                {% if answer.acepted and reject_form %}
                    <form method="POST" action="{% url 'qanda:update_answer_acceptance' pk=answer.id %}">
                        {% csrf_token %}
                        {{ reject_form }}
                        <button type="submit" class="btn btn-link">
                            <i class="fa fa-times" aria-hidden="true"> </i>
                            Reject
                        </button>
                    </form>
                {% elif accept_form %}
                    <form method="POST" action="{% url 'qanda:update_answer_acceptance' pk=answer.id %}">
                        {% csrf_token %}
                        {{ accept_form }}
                        <button type="submit" class="btn btn-link" title="Accept answer">
                            <i class="fa fa-check-circle" aria-hidden="true"> </i>
                            Accept
                        </button>
                    </form>
                {% endif %}
            </div>

            <div class="col-sm-9 col-md-10">
                <div class="body"> {{ answer.answer|markdownify }} </div>
                <div class="meta font-weight-light"> Answered by {{ answer.user }} on {{ answer.created }} </div>
            </div>
        </li>
    {% empty %}
        <li class="answer"> No answers yet ! </li>
    {% endfor %}
</ul>

qanda/templates/qanda/common/post_answer.html
{% load crispy_forms_tags %}

<div class="col-sm-12">
    <h3> Post you answer </h3>
    <form method="POST" action="{% url 'qanda:answer_question' pk=question.id %}">
        {{ answer_form|crispy }}
        {% csrf_token %}
        <button class="btn btn-primary" type="submit" name="action" value="PREVIEW"> Preview</button>
        <button class="btn btn-primary" type="submit" name="action" value="SAVE"> Answer</button>
    </form>
</div>

qanda/templates/qanda/create_answer.html
{% extends 'base.html' %}
{% load markdownify %}

{% block body %}
    {% include 'qanda/common/display_question.html' %}

    {% if preview %}
        <div class="card question-preview">
            <div class="card-header"> Answer Preview </div>
            <div class="card-body"> {{ preview|markdownify }} </div>
        </div>
    {% endif %}

    {% include 'qanda/common/post_answer.html' with answer_form=form %}

{% endblock %}

qanda/templates/qanda/question_archive_day.html
{% extends 'base.html' %}

{% block title %}
    Questions on {{ day }}
{% endblock %}

{% block body %}
    <div class="col-sm-12">
        <h1> Highest voted questions of {{ day }} </h1>

        <ul>
            {% for question in object_list %}
                <li>
                    <a href="{{ question.get_absolute_url }}"> {{ question }} </a>
                    by {{ question.user }} on {{ question.created }}
                </li>

            {% empty %}
                <li> No questions today </li>
            {% endfor %}
        </ul>

        <div>
            {% if previous_day %}
                <a href="{% url 'qanda:daily_questions' year=previous_day.year month=previous_day.month day=previous_day.day %}">
                    << Previous day </a>
            {% endif %}

            {% if next_day %}
                <a href="{% url 'qanda:daily_questions' year=next_day.year month=next_day.month day=next_day.day %}">
                    Next day >> </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

qanda/templates/qanda/question_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ question.title }} - {{ block.super }}
{% endblock %}

{% block body %}
    {% include 'qanda/common/display_question.html' %}
    {% include 'qanda/common/list_answers.html' %}

    {% if user.is_authenticated %}
        {% include 'qanda/common/post_answer.html' %}
    {% else %}
        <div> Login to post answers.</div>
    {% endif %}

{% endblock %}

qanda/templates/qanda/search.html
{% extends 'base.html' %}
{% load markdownify %}

{% block body %}
    <h2> Search </h2>

    <form method="get" class="form-inline">
        <input class="form-control mr-2" placeholder="Search" type="search" name="q" value="{{ query }}">
        <button type="submit" class="btn btn-primary"> Search</button>
    </form>

    {% if query %}
        <h3> Results from search query '{{ query }}'</h3>
        <ul class="list-unstyled search-results">
            {% for hit in hits %}
                <li>
                    <a href="{% url 'qanda:question_detail' pk=hit.id %}"> {{ hit.title }} </a>
                    <div> {{ hit.question_body|markdownify|truncatewords_html:20 }}</div>
                </li>
            {% empty %}
                <li> No results</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
    <link href="{% static 'base.css' %}" rel="stylesheet">

    <title> {% block title %} Answerly {% endblock %}</title>
</head>

<body>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
        <a class="navbar-brand" href="/"> Answerly </a>

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'qanda:ask' %}"> Ask </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'qanda:index' %}"> Today's hot question </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'qanda:days' %}"> All days </a>
            </li>

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:logout' %}"> Logout, {{ user.username }} </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:login' %}"> Login </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:register' %}"> Register </a>
                </li>
            {% endif %}

            <li class="nav-item">
                <form class="form-inline" action="{% url 'qanda:question_search' %}" method="GET">
                    <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit"> </button>
                </form>
            </li>
        </ul>
    </div>
</nav>

<div class="container">
    {% block body %} {% endblock %}
</div>
</body>
</html>